### ISSUE TITLE
Unterstützte Kaffemaschinen / Supported Coffee Makers

### ISSUE THREAD

**Issue by TheRealGenetic** [Jutta-Proto/hardware-pi#1]
Hallo,

hab die den Issue unter protokol-cpp gelesen und wollte fragen welche Kaffemaschinen den noch mit dem Quellcode hier unterstützt werden, und wie ich das erkennen kann 

Vielen Dank im Voraus.

**Comment by COM8** [comment]
Theoretisch jede Kaffeemaschine, die den [Smart Control](https://uk.jura.com/en/homeproducts/accessories/SmartConnect-Main-72167) Dongle unterstützt.
Wenn eine Verbindung über die serielle Schnittstelle herstellen werden soll, dann garantiert nur mit die JURA E6, auf der ich den Code getestet habe.
Wenn eine Verbindung über Bluetooth herstellen werden soll, dann alle, die den [Smart Control](https://uk.jura.com/en/homeproducts/accessories/SmartConnect-Main-72167) Dongle unterstützen.

===
In theory every coffee maker that supports the [Smart Control](https://uk.jura.com/en/homeproducts/accessories/SmartConnect-Main-72167) dongle.
If you want to connect via serial then for sure only the JURA E6 I tested the code on.
If you want to connect via Bluetooth, then all that supports the [Smart Control](https://uk.jura.com/en/homeproducts/accessories/SmartConnect-Main-72167) dongle.
